language: r
cache: packages

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beastscriptr
  - rsetienne/PBD/PBD

before_script:
  - Rscript -e 'devtools::install_github("richelbilderbeek/beastscriptr")'
  - Rscript -e 'devtools::install_github("rsetienne/PBD/PBD")'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
