language: r
cache: packages

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beastscriptr
  - rsetienne/PBD/PBD
  - beast-dev/RBeast

after_success:
  - Rscript -e "ribir::is_on_travis()"
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "covr::codecov()"
  - Rscript -e "goodpractice::gp()"
